<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Технический аудит проектных решений | Группа Интегра</title><meta name="description" content="Технический аудит проектов и выполненных работ по системам усиления связи: расчёты, оборудование, монтаж, документация и риски перед приёмкой."><link rel="canonical" href="https://groupintegra.ru/services/audit.php"><link rel="icon" href="/images/favicon.ico"></head><body>
<?php include '../header.php'; ?><main><section class="hero"><div class="hero-content"><div class="hero-highlight">Аудит · технический контроль</div><h1>Технический аудит системы усиления связи</h1><p>Проверяем проект и фактическую реализацию, чтобы заказчик понимал, что действительно сделано, где есть несоответствия и что потребуется исправить до приёмки.</p><div class="hero-buttons"><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Заказать аудит</button><a class="btn btn-outline" href="/gsm.php">Усиление связи</a></div></div></section>
<section><div class="container"><h2 class="section-title">Что проверяем</h2><div class="benefits-grid">
<article class="benefit-card"><h3>Проект и расчёты</h3><p>Проверяем исходные данные, расчёт покрытия, архитектуру системы, схемы и соответствие поставленной задаче.</p></article>
<article class="benefit-card"><h3>Оборудование</h3><p>Сверяем фактический состав оборудования с проектом и оцениваем его применимость в принятой архитектуре.</p></article>
<article class="benefit-card"><h3>Монтаж</h3><p>Проверяем размещение оборудования, кабельные линии, антенные элементы, маркировку и качество исполнения.</p></article>
<article class="benefit-card"><h3>Документация</h3><p>Смотрим, соответствует ли исполнительная документация фактически выполненной системе и достаточно ли её для эксплуатации.</p></article>
</div></div></section>
<section class="additional-services"><div class="container"><h2 class="section-title">Результат аудита</h2><div class="process-steps">
<div class="process-step"><span class="step-number">01</span><h3>Собираем материалы</h3><p>Проект, планы, спецификации, исполнительные документы и информацию о выполненных работах.</p></div>
<div class="process-step"><span class="step-number">02</span><h3>Проводим проверку</h3><p>Сопоставляем документацию, техническое решение и фактическое состояние объекта.</p></div>
<div class="process-step"><span class="step-number">03</span><h3>Фиксируем замечания</h3><p>Разделяем выявленные проблемы по технической значимости и этапу, на котором их необходимо устранить.</p></div>
<div class="process-step"><span class="step-number">04</span><h3>Даём рекомендации</h3><p>Формируем понятный перечень необходимых действий перед продолжением работ или приёмкой.</p></div>
</div></div></section>
<section><div class="container"><div class="cta"><h2>Нужно проверить подрядчика или готовый проект?</h2><p>Пришлите проект, спецификацию или исполнительные материалы. Определим объём проверки и исходные данные.</p><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Обсудить аудит</button></div></div></section>
</main><?php include '../footer.php'; ?></body></html>