<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Проектирование систем усиления сотовой связи | Группа Интегра</title><meta name="description" content="Проектирование систем усиления сотовой связи: обследование, расчёт покрытия, архитектура, подбор оборудования и рабочая документация."><link rel="canonical" href="https://groupintegra.ru/services/design.php"><link rel="icon" href="/images/favicon.ico"></head><body>
<?php include '../header.php'; ?><main><section class="hero"><div class="hero-content"><div class="hero-highlight">Усиление сотовой связи · проектирование</div><h1>Проектирование систем усиления связи</h1><p>Разрабатываем техническое решение от исходных измерений до рабочей документации: рассчитываем покрытие, выбираем архитектуру и состав оборудования, учитываем строительные ограничения.</p><div class="hero-buttons"><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Обсудить проект</button><a class="btn btn-outline" href="/services/measurements.php">Обследование</a></div></div></section>
<section><div class="container"><h2 class="section-title">Что входит в проектирование</h2><div class="benefits-grid">
<article class="benefit-card"><h3>Исходные данные</h3><p>Изучаем архитектурные планы, этажность, назначение помещений, требования заказчика и результаты измерений сигнала.</p></article>
<article class="benefit-card"><h3>Расчёт покрытия</h3><p>Определяем зоны, где требуется усиление, и рассчитываем размещение оборудования, кабельных линий и антенных элементов.</p></article>
<article class="benefit-card"><h3>Архитектура системы</h3><p>Формируем состав активного и пассивного оборудования с учётом площади, количества зон и технических ограничений.</p></article>
<article class="benefit-card"><h3>Рабочая документация</h3><p>Фиксируем схему, трассы, оборудование и технические решения так, чтобы по проекту можно было организовать монтаж и последующую проверку.</p></article>
</div></div></section>
<section class="additional-services"><div class="container"><h2 class="section-title">Этапы</h2><div class="process-steps">
<div class="process-step"><span class="step-number">01</span><h3>Исходные данные</h3><p>Получаем планы, ТЗ и результаты обследования.</p></div>
<div class="process-step"><span class="step-number">02</span><h3>Расчёт</h3><p>Определяем архитектуру и параметры системы.</p></div>
<div class="process-step"><span class="step-number">03</span><h3>Согласование</h3><p>Уточняем состав оборудования и технические решения.</p></div>
<div class="process-step"><span class="step-number">04</span><h3>Документация</h3><p>Передаём материалы для реализации и контроля монтажа.</p></div>
</div></div></section>
<section><div class="container"><div class="cta"><h2>Нужен проект под конкретный объект?</h2><p>Для предварительной оценки достаточно плана объекта, краткого ТЗ и информации о проблемных зонах связи.</p><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Отправить исходные данные</button></div></div></section>
</main><?php include '../footer.php'; ?></body></html>