<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Монтаж систем усиления сотовой связи | Группа Интегра</title><meta name="description" content="Монтаж систем усиления сотовой связи: оборудование, антенно-фидерная инфраструктура, кабельные трассы, настройка, измерения и подготовка к сдаче."><link rel="canonical" href="https://groupintegra.ru/services/installation.php"><link rel="icon" href="/images/favicon.ico"></head><body>
<?php include '../header.php'; ?><main><section class="hero"><div class="hero-content"><div class="hero-highlight">Усиление сотовой связи · монтаж</div><h1>Монтаж систем усиления связи</h1><p>Выполняем монтаж оборудования и антенно-фидерной инфраструктуры по согласованному проектному решению и с контролем качества до сдачи системы.</p><div class="hero-buttons"><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Обсудить монтаж</button><a class="btn btn-outline" href="/services/design.php">Проектирование</a></div></div></section>
<section><div class="container"><h2 class="section-title">Что входит в монтаж</h2><div class="benefits-grid">
<article class="benefit-card"><h3>Подготовка</h3><p>Изучаем проект, рабочие чертежи, спецификацию, трассы и фронт работ перед выходом на объект.</p></article>
<article class="benefit-card"><h3>Оборудование и антенны</h3><p>Устанавливаем активное оборудование, делители, ответвители, антенны и другие элементы системы согласно проекту.</p></article>
<article class="benefit-card"><h3>Кабельные линии</h3><p>Прокладываем и маркируем линии, соблюдая согласованные трассы, радиусы изгиба, крепление и требования к совместной прокладке.</p></article>
<article class="benefit-card"><h3>Настройка и проверка</h3><p>Проверяем соединения, параметры системы и фактическое покрытие после выполнения монтажных работ.</p></article>
</div></div></section>
<section class="additional-services"><div class="container"><h2 class="section-title">Как проходит работа</h2><div class="process-steps">
<div class="process-step"><span class="step-number">01</span><h3>Подготовка</h3><p>Сверяем проект и готовность фронта работ.</p></div>
<div class="process-step"><span class="step-number">02</span><h3>Монтаж</h3><p>Устанавливаем оборудование и кабельную инфраструктуру.</p></div>
<div class="process-step"><span class="step-number">03</span><h3>Настройка</h3><p>Проверяем соединения и параметры системы.</p></div>
<div class="process-step"><span class="step-number">04</span><h3>Измерения</h3><p>Контролируем фактический результат и замечания.</p></div>
</div></div></section>
<section><div class="container"><div class="cta"><h2>Есть готовый проект?</h2><p>Пришлите проект и планы объекта. Определим состав монтажных работ, исходные условия и следующий этап.</p><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Обсудить монтаж</button></div></div></section>
</main><?php include '../footer.php'; ?></body></html>