<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Техническое обслуживание систем связи | Группа Интегра</title><meta name="description" content="Техническое обслуживание систем усиления сотовой связи: диагностика, регламентные проверки, поиск неисправностей, измерения и восстановление работоспособности."><link rel="canonical" href="https://groupintegra.ru/services/support.php"><link rel="icon" href="/images/favicon.ico"></head><body>
<?php include '../header.php'; ?><main><section class="hero"><div class="hero-content"><div class="hero-highlight">Поддержка · эксплуатация</div><h1>Техническое обслуживание систем связи</h1><p>Поддерживаем работоспособность системы после запуска: диагностируем проблемы, выполняем регламентные работы, проверяем параметры и помогаем восстановить нормальную работу.</p><div class="hero-buttons"><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Обсудить обслуживание</button><a class="btn btn-outline" href="/gsm.php">Усиление связи</a></div></div></section>
<section><div class="container"><h2 class="section-title">Что входит в обслуживание</h2><div class="benefits-grid">
<article class="benefit-card"><h3>Диагностика</h3><p>Проверяем оборудование, соединения, кабельную часть и другие элементы системы, чтобы определить причину проблемы.</p></article>
<article class="benefit-card"><h3>Регламентные проверки</h3><p>Проводим плановые осмотры и контроль состояния системы, чтобы выявлять неисправности до серьёзного отказа.</p></article>
<article class="benefit-card"><h3>Измерения</h3><p>При необходимости повторяем контрольные измерения и сравниваем результат с рабочими параметрами объекта.</p></article>
<article class="benefit-card"><h3>Устранение неисправностей</h3><p>После диагностики согласуем необходимые работы и восстанавливаем работоспособность системы.</p></article>
</div></div></section>
<section class="additional-services"><div class="container"><h2 class="section-title">Как проходит обращение</h2><div class="process-steps">
<div class="process-step"><span class="step-number">01</span><h3>Обращение</h3><p>Фиксируем проблему, объект и доступные материалы по системе.</p></div>
<div class="process-step"><span class="step-number">02</span><h3>Диагностика</h3><p>Определяем техническую причину и объём необходимых работ.</p></div>
<div class="process-step"><span class="step-number">03</span><h3>Решение</h3><p>Согласуем ремонт, настройку, замену или другие необходимые действия.</p></div>
<div class="process-step"><span class="step-number">04</span><h3>Контроль</h3><p>Проверяем восстановление системы и фиксируем выполненный результат.</p></div>
</div></div></section>
<section><div class="container"><div class="cta"><h2>Система уже установлена, но работает нестабильно?</h2><p>Опишите объект и проблему. Если есть проект, исполнительная документация или результаты предыдущих измерений — их можно приложить к обращению.</p><button class="btn btn-primary" type="button" onclick="integraOpenModal();return false;">Обсудить обслуживание</button></div></div></section>
</main><?php include '../footer.php'; ?></body></html>